/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oracle from "./oracle";
export type { oracle };
export type { ERC20Paymaster } from "./ERC20Paymaster";
