/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAlchemyNonceManager,
  IAlchemyNonceManagerInterface,
} from "../../../../contracts/erc4337/interfaces/IAlchemyNonceManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint192",
        name: "key",
        type: "uint192",
      },
    ],
    name: "getNonce",
    outputs: [
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint192",
        name: "key",
        type: "uint192",
      },
    ],
    name: "incrementNonce",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAlchemyNonceManager__factory {
  static readonly abi = _abi;
  static createInterface(): IAlchemyNonceManagerInterface {
    return new Interface(_abi) as IAlchemyNonceManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAlchemyNonceManager {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAlchemyNonceManager;
  }
}
