/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IWhitelistPaymaster } from "./IWhitelistPaymaster";
export type { WhitelistPaymaster } from "./WhitelistPaymaster";
